#!/bin/bash
#SBATCH --ntasks=40
#SBATCH --cpus-per-task=2
#SBATCH --mem=200000MB
#SBATCH --time=00:59:00
#SBATCH -p regular11
#SBATCH --output=i_rhocut.out
#SBATCH --error=i_rhocut.err
#SBATCH --mail-type=END
#SBATCH --mail-user=atan@sissa.it

. /home/atan/bin/module_load_gnu

# define sequence for ecutwfc
ecutwfc=($(seq 10 10 70))

# creates folder for cutoff
cd rhocutoff/
mkdir -p wfclower
cd wfclower/

# do loop for k cutoff
for wfcut in ${ecutwfc[@]}
do

mkdir -p wfclower${wfcut}
cd wfclower$wfcut/

# define variable for ecutrho as a function of ecwfc

cat << EOF > Sc_wfclower${wfcut}.scf.in
 &control 
	calculation='scf'
	restart_mode='from_scratch',
	prefix='scandium',
	pseudo_dir='../../../',
	outdir='sc_rhocut.out'
 /
 &system
	ibrav=4
	celldm(1)=6.2531037
	celldm(3)=1.594
	nat=2
	ntyp=1
	ecutwfc=$wfcut
	ecutrho=320
	occupations='smearing'
	smearing='mv'
	degauss=0.02

 /
 &electrons
	mixing_mode='plain'
	mixing_beta=0.7
	diagonalization='david'
	conv_thr=1.0d-8
 /

ATOMIC_SPECIES
 Sc 44.596 Sc.pz-spn-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS crystal
 Sc 0.00 0.00 0.00
 Sc 0.666666666667 0.333333333333 0.5
K_POINTS automatic
12 12 8 0 0 0
EOF

#change directory to where qe directory is
mpirun -np 20 /home/atan/q-e-qe-7.2/bin/pw.x < Sc_wfclower${wfcut}.scf.in > Sc_wfclower${wfcut}.scf.out

#uncomment to remove the output file
# rm -r sc_rhocut.out 
 
cd ..

done
