#!/bin/bash
#SBATCH --ntasks=16
#SBATCH --cpus-per-task=2
#SBATCH --mem=50GB
#SBATCH --time=06:29:00
#SBATCH -A Sis23_degironc_1
#SBATCH -p boost_usr_prod
#SBATCH --output=vc_lower90.out
#SBATCH --error=vc_lower90.err
#SBATCH --mail-type=END
#SBATCH --mail-user=atan@sissa.it

cd vcrelax/

mkdir -p wfclower90
cd wfclower90/

wfclower=($(seq 60 10 80))

for wfcut in ${wfclower[@]}
do

mkdir -p wfc${wfcut}
cd wfc$wfcut/

cat << EOF > Sc_iii_lower90${wfcut}.vcrelax.in
 &control
	calculation='vc-relax'
	restart_mode='from_scratch',
	prefix='scandium',
	pseudo_dir='../../../',
	outdir='sc_vcrelax.out'
 /

 &system
	ibrav=4
	celldm(1)=6.2531037
	celldm(3)=1.594
	nat=2
	ntyp=1
	ecutwfc=$wfcut
	ecutrho=360
	occupations='smearing'
	smearing='mv'
	degauss=0.02
 /

 &electrons
	mixing_mode='plain'
	mixing_beta=0.7
	diagonalization='david'
	conv_thr=1.0d-8
 /

 &ions
 /

 &cell
	press=0
 /

ATOMIC_SPECIES
 Sc 44.596 Sc.pz-spn-kjpaw_psl.1.0.0.UPF

ATOMIC_POSITIONS crystal
 Sc 0.00 0.00 0.00
 Sc 0.666666666667 0.333333333333 0.5

K_POINTS automatic
 12 12 8 0 0 0
EOF

mpirun -np $SLURM_NTASKS $PWX_DIR < Sc_iii_lower90${wfcut}.vcrelax.in > Sc_iii_lower90${wfcut}.vcrelax.out

cd ..

done 
