#!/bin/sh


# set needed environment variables from QE base
. ../../q-e-qe-7.2/environment_variables

# set environment variables for THERMO_PW
. ./environment_tpw.job

# name variables and echo command
NAME="sc"
ECHO="echo"

mkdir tpw_results
cd tpw_results


echo $PWDIR
THERMO_PW_COMMAND="$PREFIX $PWDIR/thermo_pw.x $SUFFIX"

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST="Sc.pz-spn-kjpaw_psl.1.0.0.UPF"

echo 'creating thermo_pw file'
# thermo_pw commands
cat > thermo_control << EOF
 &INPUT_THERMO
  what='scf_ph'
  nq1_d=128, nq2_d=128, nq3_d=128
 /
EOF

echo 'creating input file '$NAME'.scf.in'
# Sc.scf.in geometry and data copied from converged vcrelax params
cat > $NAME.scf.in << EOF
 &control
	calculation='scf'
	prefix='$NAME',
	pseudo_dir = '$PSEUDODIR',
	outdir='$OUTDIR'
 /
 &system
	ibrav=4
	celldm(1)=6.09368707
	celldm(3)=1.54636503
	nat=2
	ntyp=1
	ecutwfc=70
	ecutrho=360
	occupations='smearing'
	smearing='mv'
	degauss=0.02
 /
 &electrons
	mixing_mode='plain'
	mixing_beta=0.7
	diagonalization='david'
	conv_thr=1.0d-10
 /

ATOMIC_SPECIES
 Sc 44.596 $PSEUDO_LIST 

ATOMIC_POSITIONS crystal
 Sc 0.00 0.00 0.00
 Sc 0.666666666667 0.333333333333 0.5

K_POINTS automatic
12 12 8 1 1 1
EOF

echo 'creating ph_control file'
# phonons
cat > ph_control << EOF
phonons at Gamma
 &inputph
	prefix='$NAME',
	ldisp=.false.
	fildyn='sc.dyn.xml',
	nq1=4,
	nq2=4,
	nq3=2,
	tr2_ph=1.0d-16,
 /
0 0 0
EOF

$ECHO " running the phonon calculation on a 12x12x8 mesh"

$ECHO $THERMO_PW_COMMAND  $NAME.scf.in  $NAME.scf.out
$THERMO_PW_COMMAND < $NAME.scf.in > $NAME.scf.out

cd ..

