#!/bin/sh


# set needed environment variables from QE base
. ~/q-e-qe-7.2/environment_variables

# set environment variables for THERMO_PW
. ../environment_tpw.job

# name variables and echo command
NAME="sc"
ECHO="echo"


echo $PWDIR
THERMO_PW_COMMAND="$PREFIX $PWDIR/thermo_pw.x $SUFFIX"

# required executables and pseudopotentials
BIN_LIST="thermo_pw.x"
PSEUDO_LIST="Sc.pz-spn-kjpaw_psl.1.0.0.UPF"



declare -i iter=0

# read from spec_k_coords.dat (see end of do loop)
while read p
do


# tmp file cleaned at each wfc
mkdir -p tmp
mkdir -p special${iter}
cd special$iter/

echo 'creating thermo_pw file'
cat > thermo_control << EOF
 &INPUT_THERMO
  what='scf_ph'
  nq1_d=128, nq2_d=128, nq3_d=128
 /
EOF

echo 'creating input file '$NAME'.specialk'$iter'.scf.in'
cat > $NAME.specialk$iter.scf.in << EOF
 &control
	calculation='scf'
	prefix='$NAME',
	pseudo_dir = '$PSEUDODIR',
	outdir='$OUTDIR'
 /
 &system
	ibrav=4
	celldm(1)=6.09368707
	celldm(3)=1.54636503
	nat=2
	ntyp=1
	ecutwfc=70
	ecutrho=320
	occupations='smearing'
	smearing='mv'
	degauss=0.02
 /
 &electrons
	mixing_mode='plain'
	mixing_beta=0.7
	diagonalization='david'
	conv_thr=1.0d-10
 /

ATOMIC_SPECIES
 Sc 44.596 $PSEUDO_LIST 

ATOMIC_POSITIONS crystal
 Sc 0.00 0.00 0.00
 Sc 0.666666666667 0.333333333333 0.5

K_POINTS automatic
12 12 12 1 1 1
EOF

echo 'creating ph_control file'
cat > ph_control << EOF
phonons at Gamma
 &inputph
	prefix='$NAME',
	ldisp=.false.
	fildyn='sc.dyn.xml',
	nq1=4,
	nq2=4,
	nq3=2,
	tr2_ph=1.0d-16,
 /
$p
EOF

$ECHO " running the phonon calculation for kvec="$p

$THERMO_PW_COMMAND < $NAME.specialk$iter.scf.in > $NAME.specialk$iter.scf.out

cd ..
rm -r tmp
iter=$((iter+1))
done < spec_k_coords.dat
